"""products table

Revision ID: 3d7a7f47dac4
Revises: fef19640c317
Create Date: 2026-04-18 17:19:04.740749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d7a7f47dac4'
down_revision: Union[str, Sequence[str], None] = 'fef19640c317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'expried_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'expried_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
